# Generated by Django 5.1.3 on 2024-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hive_password_hive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='vanish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
