# Generated by Django 5.1.3 on 2024-11-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_message_vanish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='vanish_mode',
            field=models.BooleanField(default=False),
        ),
    ]
