# Generated by Django 5.1.3 on 2024-11-29 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_message_vanish_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('queen', 'Queen'), ('bee', 'Bee'), ('custom', 'Custom')], default='bee', max_length=20)),
                ('custom_role_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hive')},
            },
        ),
    ]
