# Generated by Django 5.1.3 on 2024-11-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userrole'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('queen', 'Queen'), ('moderator', 'Moderator'), ('bee', 'Bee')], default='bee', max_length=20),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='custom_role_name',
        ),
    ]
