# Generated by Django 5.1.3 on 2024-12-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_message_vanish_mode_message_vanish_time_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='playlist_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
